Repository Team-Swamp/CaptureGraafsmeer, pull requests merged in 2024-03, with the labels that each got.

#2 readme/patch-1
  README.md
Labels: documentation, ready for review

#3 feature/interactable-ray
  Assets/Input/Input Actions.inputactions
  Assets/Input/Input Actions.inputactions.meta
  Assets/Scripts/Player/InputParser.cs
  Assets/Scripts/Player/InputParser.cs.meta
Labels: code, new, ready for review

#5 hotfix/input-namespace
  Assets/Scripts/Player/LocationUpdater.cs
  Assets/Scripts/Player/NewInput.meta
  Assets/Scripts/Player/NewInput/InputParser.cs
  Assets/Scripts/Player/NewInput/InputParser.cs.meta
Labels: bug, code, ready for merge

#4 feature/gitworkflow-meta-files-check
  .github/workflows/MetaFilesCheck.yml
  Assets/Animations/EmptyFolder.txt
  Assets/Animations/EmptyFolder.txt.meta
  Assets/Art/Models/EmptyFolder.txt
  Assets/Art/Models/EmptyFolder.txt.meta
  Assets/Audio/Music/EmptyFolder.txt
  Assets/Audio/Music/EmptyFolder.txt.meta
  Assets/Audio/Sound Effects/EmptyFolder.txt
  Assets/Audio/Sound Effects/EmptyFolder.txt.meta
  Assets/Prefabs/Art/Chracters/EmptyFolder.txt
  Assets/Prefabs/Art/Chracters/EmptyFolder.txt.meta
  Assets/Prefabs/Art/Environment/EmptyFolder.txt
  Assets/Prefabs/Art/Environment/EmptyFolder.txt.meta
  Assets/Prefabs/Art/Props/EmptyFolder.txt
  Assets/Prefabs/Art/Props/EmptyFolder.txt.meta
  Assets/Prefabs/Funcinal/UI/Canvas/EmptyFolder.txt
  Assets/Prefabs/Funcinal/UI/Canvas/EmptyFolder.txt.meta
  Assets/Prefabs/Funcinal/UI/World/EmptyFolder.txt
  Assets/Prefabs/Funcinal/UI/World/EmptyFolder.txt.meta
  Assets/Scenes/Art/EmptyFolder.txt
  Assets/Scenes/Art/EmptyFolder.txt.meta
  Assets/ScriptableObjects/EmptyFolder.txt
  Assets/ScriptableObjects/EmptyFolder.txt.meta
  Assets/Scripts/Framework/Enums/EmptyFolder.txt
  Assets/Scripts/Framework/Enums/EmptyFolder.txt.meta
  Assets/Scripts/Framework/ScriptableObjects/EmptyFolder.txt
  Assets/Scripts/Framework/ScriptableObjects/EmptyFolder.txt.meta
  Assets/Scripts/NPC/EmptyFolder.txt
  Assets/Scripts/NPC/EmptyFolder.txt.meta
  Assets/Scripts/UI/World/EmptyFolder.txt
  Assets/Scripts/UI/World/EmptyFolder.txt.meta
  Assets/Textures/EmptyFolder.txt
  Assets/Textures/EmptyFolder.txt.meta
Labels: code, ready for review
