Repository Team-Swamp/CaptureGraafsmeer, pull requests merged in 2024-06, with the labels that each got.

#74 hotfix/UI-Statemachine
  Assets/Scenes/Sprint3.unity
Labels: bug, ready for merge

#76 Feature/camera zoom
  Assets/Prefabs/Funcinal/UI/Canvas/MainCanvas.prefab
  Assets/Scenes/Sprint4.unity
  Assets/Scripts/UI/Canvas/PhotoTaking/PhotoTaker.cs
  Assets/Sprites/UI_ZoomIcon.png
  Assets/Sprites/UI_ZoomIcon.png.meta
Labels: code, new, ready for review

#77 hotfix/class-icons
  Assets/Scenes/Testing/CustomClassIcon.unity
  Assets/Scenes/Testing/CustomClassIcon.unity.meta
  Assets/Scripts/Framework/GeoLocation/CoordinatesTransform.cs.meta
  Assets/Scripts/Framework/GeoLocation/RouteHighlighter.cs.meta
  Assets/Scripts/Framework/PhoneCamera/PhotoInteractable.cs.meta
  Assets/Scripts/UI/Canvas/Introduction/IntroductionPopup.cs.meta
  Assets/Scripts/UI/Canvas/PhotoBookSystem/PhotoBook.cs.meta
  Assets/Scripts/UI/Canvas/PhotoTaking/PhotoTaker.cs.meta
  Assets/Scripts/UI/Canvas/RouteLineSettings/ColorPicker.cs.meta
  Assets/Sprites/CustomClassIcons.meta
  Assets/Sprites/CustomClassIcons/T_RouteHighlighterIcon.png
  Assets/Sprites/CustomClassIcons/T_RouteHighlighterIcon.png.meta
  Assets/Sprites/CustomClassIcons/T_RouteHighlighterIconColored.png
  Assets/Sprites/CustomClassIcons/T_RouteHighlighterIconColored.png.meta
Labels: new, ready for merge
