Repository Team-Swamp/CaptureGraafsmeer, pull requests merged in 2024-04, with the labels that each got.

#8 feature/camera-rotation
  Assets/Prefabs/Funcinal/Entities/Player.prefab
  Assets/Scenes/Testing/CameraRotation Test.unity
  Assets/Scenes/Testing/CameraRotation Test.unity.meta
Labels: new, ready for merge

#9 Feature/interactables
  Assets/Input/Input Actions.inputactions
  Assets/Prefabs/Funcinal/Entities/Photo interacatable.prefab
  Assets/Prefabs/Funcinal/Entities/Photo interacatable.prefab.meta
  Assets/Prefabs/Funcinal/Entities/Player.prefab
  Assets/Prefabs/Funcinal/UI/Canvas/EmptyFolder.txt
  Assets/Prefabs/Funcinal/UI/Canvas/Photo maker.prefab
  Assets/Scenes/Boot.unity
  Assets/Scenes/Testing/Map with photo.unity
  Assets/Scenes/Testing/Map with photo.unity.meta
  Assets/Scenes/Testing/PhotoTaking.unity
  Assets/ScriptableObjects/EmptyFolder.txt
  Assets/ScriptableObjects/Photos/BurgerKing.asset
  Assets/ScriptableObjects/Photos/BurgerKing.asset.meta
  Assets/ScriptableObjects/Photos/MA.asset
  Assets/ScriptableObjects/Photos/MA.asset.meta
  Assets/ScriptableObjects/Photos/Stoplichten.asset
  Assets/ScriptableObjects/Photos/Stoplichten.asset.meta
  Assets/ScriptableObjects/Photos/TropicalDrimo.asset
  Assets/ScriptableObjects/Photos/TropicalDrimo.asset.meta
  Assets/Scripts/Framework/GeoLocation/CoordinatesTransform.cs
  Assets/Scripts/Framework/PhoneCamera/PhotoInteractable.cs
  Assets/Scripts/Framework/PhoneCamera/PhotoInteractable.cs.meta
  Assets/Scripts/Framework/ScriptableObjects/EmptyFolder.txt
  Assets/Scripts/UI/Canvas/PhotoCamera/PhotoTaker.cs
  ProjectSettings/EditorBuildSettings.asset
  ProjectSettings/TagManager.asset
Labels: code, ready for merge

#10 hotfix/rotating-camera
  Assets/Prefabs/Funcinal/Entities/Player.prefab
Labels: bug, ready for merge

#11 feature/scene building
  Assets/Prefabs/Funcinal/Entities/Player.prefab
  Assets/Prefabs/Funcinal/Systems/Route.prefab
  Assets/Prefabs/Funcinal/Systems/Route.prefab.meta
  Assets/Scenes/Boot.unity
  Assets/Scenes/Sprint1.unity
  Assets/Scenes/Sprint1.unity.meta
  Assets/Scripts/Framework/GeoLocation/RouteHighlighter.cs
  ProjectSettings/EditorBuildSettings.asset
Labels: code, ready for review

#13 readme/patch-2
  README.md
Labels: documentation, ready for merge

#12 Art/FrankendaelGate
  Assets/Art/Models/EmptyFolder.txt
  Assets/Art/Models/SM_Frankendael_Gate.fbx
  Assets/Art/Models/SM_Frankendael_Gate.fbx.meta
  Assets/Materials/M_FrankenDael_Gate.mat
  Assets/Materials/M_FrankenDael_Gate.mat.meta
  Assets/Prefabs/Art/Props/EmptyFolder.txt
  Assets/Prefabs/Art/Props/FrankendaelGate.prefab
  Assets/Prefabs/Art/Props/FrankendaelGate.prefab.meta
  Assets/Scene_Dylan.unity
  Assets/Scene_Dylan.unity.meta
  Assets/Textures/-FrankenDael_Gate.meta
  Assets/Textures/-FrankenDael_Gate/T_FrankenDael_Gate_D.png
  Assets/Textures/-FrankenDael_Gate/T_FrankenDael_Gate_D.png.meta
  Assets/Textures/-FrankenDael_Gate/T_FrankenDael_Gate_MT.png
  Assets/Textures/-FrankenDael_Gate/T_FrankenDael_Gate_MT.png.meta
  Assets/Textures/-FrankenDael_Gate/T_FrankenDael_Gate_N.png
  Assets/Textures/-FrankenDael_Gate/T_FrankenDael_Gate_N.png.meta
  Assets/Textures/EmptyFolder.txt
Labels: art, new, work in progress

#14 hotfix/remove-print
  Assets/Scripts/Framework/GeoLocation/RouteHighlighter.cs
Labels: code, ready for merge

#16 art/courthousewgm
  Assets/Art/Models/SM_CourthouseWGM.fbx
  Assets/Art/Models/SM_CourthouseWGM.fbx.meta
  Assets/Materials/M_CourthouseWGM.mat
  Assets/Materials/M_CourthouseWGM.mat.meta
  Assets/Prefabs/Art/Props/CourthouseWGM.prefab
  Assets/Prefabs/Art/Props/CourthouseWGM.prefab.meta
  Assets/Scenes/Art/EmptyFolder.txt
  Assets/Scenes/Art/Scene_Dylan.unity
  Assets/Scenes/Art/Scene_Dylan.unity.meta
  Assets/Scenes/Art/TaquilaArt.unity
  Assets/Scenes/Art/TaquilaArt.unity.meta
  Assets/Textures/T_CourthouseWGM.png
  Assets/Textures/T_CourthouseWGM.png.meta
Labels: art, new, ready for merge

#20 art/CelShader
  Assets/Materials/CelShading.meta
  Assets/Materials/CelShading/M_CelShade.mat
  Assets/Materials/CelShading/M_CelShade.mat.meta
  Assets/Scenes/Testing/CelShading.unity
  Assets/Scenes/Testing/CelShading.unity.meta
  Assets/Shaders/CelShader.shadergraph
  Assets/Shaders/CelShader.shadergraph.meta
Labels: art, new, ready for review

#23 feature/smooth-player-movement
  Assets/Prefabs/Funcinal/Entities/Player.prefab
  Assets/Scenes/Testing/Photobook.unity
  Assets/Scripts/Framework/GeoLocation/CoordinatesTransform.cs
Labels: code, ready for merge

#24 Feature/camera culling
  Assets/Prefabs/Art/Props/ArtpieceKruislaan.prefab
  Assets/Prefabs/Art/Props/BattleOfWatergraafsmeer.prefab
  Assets/Prefabs/Art/Props/ChildcareFS.prefab
  Assets/Prefabs/Art/Props/CourthouseWGM.prefab
  Assets/Prefabs/Art/Props/FrankendaelGate.prefab
  Assets/Prefabs/Funcinal/Entities/Player.prefab
  Assets/Scenes/Testing/FrustumCulling.unity
  Assets/Scenes/Testing/FrustumCulling.unity.meta
  Assets/Scripts/Environment/FrustumCulling.cs
  Assets/Scripts/Environment/FrustumCulling.cs.meta
  ProjectSettings/TagManager.asset
Labels: code, new, ready for merge

#25 art/hofkerk
  Assets/Materials/M_Hofkerk.mat
  Assets/Materials/M_Hofkerk.mat.meta
  Assets/Models/SM_Hofkerk.fbx
  Assets/Models/SM_Hofkerk.fbx.meta
  Assets/Prefabs/Art/Props/Hofkerk.prefab
  Assets/Prefabs/Art/Props/Hofkerk.prefab.meta
  Assets/Scenes/Art/Scene_Lisa.unity
  Assets/Scenes/Art/Scene_Lisa.unity.meta
  Assets/Textures/T_Hofkerk_D.png
  Assets/Textures/T_Hofkerk_D.png.meta
Labels: art, new, ready for merge

#26 readme/patch-3
  README.md
Labels: documentation, ready for merge

#27 Feature/camera panel
  Assets/Fonts.meta
  Assets/Fonts/calibri-regular SDF.asset
  Assets/Fonts/calibri-regular SDF.asset.meta
  Assets/Fonts/calibri-regular.ttf
  Assets/Fonts/calibri-regular.ttf.meta
  Assets/Prefabs/Funcinal/UI/Canvas/CameraPanel.prefab
  Assets/Prefabs/Funcinal/UI/Canvas/CameraPanel.prefab.meta
  Assets/Scenes/Testing/CameraPanel.unity
  Assets/Scenes/Testing/CameraPanel.unity.meta
  Assets/Scripts/Framework/PhoneCamera/PhotoInteractable.cs
  Assets/Scripts/UI/Canvas/PhotoBookSystem.meta
  Assets/Scripts/UI/Canvas/PhotoBookSystem/Page.cs
  Assets/Scripts/UI/Canvas/PhotoBookSystem/Page.cs.meta
  Assets/Scripts/UI/Canvas/PhotoBookSystem/PhotoBook.cs
  Assets/Scripts/UI/Canvas/PhotoBookSystem/PhotoBook.cs.meta
  Assets/Scripts/UI/Canvas/PhotoTaking.meta
  Assets/Scripts/UI/Canvas/PhotoTaking/CameraPanel.cs
  Assets/Scripts/UI/Canvas/PhotoTaking/CameraPanel.cs.meta
  Assets/Scripts/UI/Canvas/PhotoTaking/PhotoTaker.cs
  Assets/Scripts/UI/Canvas/PhotoTaking/PhotoTaker.cs.meta
  Assets/Swzwij/Crayon/CrayonBox/Fonts.png
  Assets/Swzwij/Crayon/CrayonBox/Fonts.png.meta
Labels: code, new, ready for merge

#28 Art/Pieternieuwlandcollege
  Assets/Materials/M_Pieter_Nieuwland_College.mat
  Assets/Materials/M_Pieter_Nieuwland_College.mat.meta
  Assets/Models/SM_Pieter_Nieuwland_College.fbx
  Assets/Models/SM_Pieter_Nieuwland_College.fbx.meta
  Assets/Prefabs/Art/Props/PieterNieuwlandCollege.prefab
  Assets/Prefabs/Art/Props/PieterNieuwlandCollege.prefab.meta
  Assets/Scenes/Art/Scene_Dylan.unity
  Assets/Textures/T_Pieter_Nieuwland_College_D.png
  Assets/Textures/T_Pieter_Nieuwland_College_D.png.meta
Labels: art, new, ready for merge

#29 Art/FountainHogeweg
  Assets/Materials/M_Fountain_Hogeweg.mat
  Assets/Materials/M_Fountain_Hogeweg.mat.meta
  Assets/Materials/M_Fountain_Particle.mat
  Assets/Materials/M_Fountain_Particle.mat.meta
  Assets/Models/SM_Fountain_Hogeweg.fbx
  Assets/Models/SM_Fountain_Hogeweg.fbx.meta
  Assets/Models/SM_Raindrop.obj
  Assets/Models/SM_Raindrop.obj.meta
  Assets/Prefabs/Art/Props/FountainHogeweg.prefab
  Assets/Prefabs/Art/Props/FountainHogeweg.prefab.meta
  Assets/Prefabs/Particles.meta
  Assets/Prefabs/Particles/Fountain.meta
  Assets/Prefabs/Particles/Fountain/PS_FountainWater.prefab
  Assets/Prefabs/Particles/Fountain/PS_FountainWater.prefab.meta
  Assets/Scenes/Art/Scene_Dylan.unity
  Assets/Textures/PointsOfIntress/T_Fountain_hogeweg_D.png
  Assets/Textures/PointsOfIntress/T_Fountain_hogeweg_D.png.meta
  Assets/Textures/T_Raindrop.png
  Assets/Textures/T_Raindrop.png.meta
Labels: art, new, ready for review

#31 art/mavo
  Assets/Materials/M_Mavo.mat
  Assets/Materials/M_Mavo.mat.meta
  Assets/Models/SM_Mavo.fbx
  Assets/Models/SM_Mavo.fbx.meta
  Assets/Prefabs/Art/Props/Mavo.prefab
  Assets/Prefabs/Art/Props/Mavo.prefab.meta
  Assets/Scenes/Art/Scene_Lisa.unity
  Assets/Textures/T_Mavo_D.jpg
  Assets/Textures/T_Mavo_D.jpg.meta
Labels: art, new, ready for merge

#33 hotfix/frustum-culling
  Assets/Prefabs/Art/Props/ArtpieceKruislaan.prefab
  Assets/Prefabs/Art/Props/BattleOfWatergraafsmeer.prefab
  Assets/Prefabs/Art/Props/ChildcareFS.prefab
  Assets/Prefabs/Art/Props/CourthouseWGM.prefab
  Assets/Prefabs/Art/Props/FountainHogeweg.prefab
  Assets/Prefabs/Art/Props/FrankendaelGate.prefab
  Assets/Prefabs/Art/Props/Hofkerk.prefab
  Assets/Prefabs/Art/Props/Mavo.prefab
  Assets/Prefabs/Art/Props/PieterNieuwlandCollege.prefab
  Assets/Scenes/Testing/FrustumCulling.meta
  Assets/Scenes/Testing/FrustumCulling.unity
  Assets/Scripts/Environment/FrustumCulling.cs
  ProjectSettings/TagManager.asset
Labels: bug, code, ready for merge

#35 hotfix/meta-file
  Assets/Scenes/Testing/FrustumCulling.meta
  Assets/Scripts/Environment/FrustumCulling.cs.meta
Labels: bug, code, ready for merge

#34 art/paintings
  Assets/Materials/M_Painting_Buys_ballot.mat
  Assets/Materials/M_Painting_Buys_ballot.mat.meta
  Assets/Materials/M_Painting_Galileo.mat
  Assets/Materials/M_Painting_Galileo.mat.meta
  Assets/Models/SM_Painting_Buys_Ballot.fbx
  Assets/Models/SM_Painting_Buys_Ballot.fbx.meta
  Assets/Models/SM_Painting_Galileo.fbx
  Assets/Models/SM_Painting_Galileo.fbx.meta
  Assets/Prefabs/Art/Props/PaintingBuyBallot.prefab
  Assets/Prefabs/Art/Props/PaintingBuyBallot.prefab.meta
  Assets/Prefabs/Art/Props/PaintingGalileo.prefab
  Assets/Prefabs/Art/Props/PaintingGalileo.prefab.meta
  Assets/Scenes/Art/Scene_Dylan.unity
  Assets/Textures/T_Painting_Buys_Ballot_D.png
  Assets/Textures/T_Painting_Buys_Ballot_D.png.meta
  Assets/Textures/T_Painting_Galileo_D.png
  Assets/Textures/T_Painting_Galileo_D.png.meta
Labels: art, new, ready for merge

#36 art/afcfootballfield
  Assets/Materials/M_AFC_FootballField.mat
  Assets/Materials/M_AFC_FootballField.mat.meta
  Assets/Models/SM_AFC_FootballField.fbx
  Assets/Models/SM_AFC_FootballField.fbx.meta
  Assets/Prefabs/Art/Props/FootballField.prefab
  Assets/Prefabs/Art/Props/FootballField.prefab.meta
  Assets/Scenes/Art/Scene_Dylan.unity
  Assets/Textures/T_AFC_Footballfield_D.png
  Assets/Textures/T_AFC_Footballfield_D.png.meta
Labels: art, new, ready for merge

#37 art/darwinplantsoen
  Assets/Materials/M_Darwinplantsoen.mat
  Assets/Materials/M_Darwinplantsoen.mat.meta
  Assets/Models/SM_Darwinplantsoen.fbx
  Assets/Models/SM_Darwinplantsoen.fbx.meta
  Assets/Prefabs/Art/Props/Darwinplantsoen.prefab
  Assets/Prefabs/Art/Props/Darwinplantsoen.prefab.meta
  Assets/Scenes/Art/Scene_Lisa.unity
  Assets/Textures/T_Darwinplantsoen_D.png
  Assets/Textures/T_Darwinplantsoen_D.png.meta
Labels: art, new, ready for merge

#39 hotfix/device-permissons
  Assets/Scripts/Framework/GeoLocation/CoordinatesTransform.cs
  Assets/Scripts/Framework/GeoLocation/LocationPermission.cs
  Assets/Scripts/Framework/IPermissionAsker.cs
  Assets/Scripts/Framework/IPermissionAsker.cs.meta
  Assets/Scripts/Framework/PhoneCamera/CameraPermission.cs
  Assets/Scripts/UI/Canvas/PhotoTaking/CameraPanel.cs
Labels: bug, code, ready for merge

#40 hotfix/mainbutton-placement
  Assets/Prefabs/Funcinal/UI/Canvas/MainCanvas.prefab
  Assets/Scenes/Testing/All UI.unity
  Assets/Scripts/UI/Canvas/AnimatedButton.cs
Labels: bug, code, ready for merge

#41 Feature/Camera-Blur
  Assets/Materials/Blur/M_PanelBlur.mat
  Assets/Materials/M_ChildcareFS.mat
  Assets/Prefabs/Funcinal/UI/Canvas/MainCanvas.prefab
  Assets/Scripts/UI/Canvas/PhotoTaking/CameraPanel.cs
  Assets/Scripts/UI/Canvas/PhotoTaking/PhotoTaker.cs
  Assets/Shaders/BlurShader.shadergraph
  Assets/Textures/RT_Webcam.renderTexture
  Assets/Textures/RT_Webcam.renderTexture.meta
Labels: art, code, new, ready for merge

#42 hotfix/Gaussian-Blur
  Assets/Materials/Blur/M_PanelBlur.mat
  Assets/Shaders/BlurShader.meta
  Assets/Shaders/BlurShader.shadergraph
  Assets/Shaders/BlurShader/BlurShader.shadergraph
  Assets/Shaders/BlurShader/BlurShader.shadergraph.meta
  Assets/Shaders/BlurShader/GaussianBlur.cginc
  Assets/Shaders/BlurShader/GaussianBlur.cginc.meta
  Assets/Shaders/BlurShader/GaussianBlurSubShader.shadersubgraph
  Assets/Shaders/BlurShader/GaussianBlurSubShader.shadersubgraph.meta
  Assets/Textures/RT_Webcam.renderTexture
  ProjectSettings/ProjectSettings.asset
Labels: art, bug, ready for merge
