Repository Team-Swamp/CaptureGraafsmeer, pull requests merged in 2024-05, with the labels that each got.

#47 Art/Tennisfield
  Assets/Materials/M_Tennis_Field.mat
  Assets/Materials/M_Tennis_Field.mat.meta
  Assets/Models/SM_Tennis_Field.fbx
  Assets/Models/SM_Tennis_Field.fbx.meta
  Assets/Prefabs/Art/Props/Tennisfield.prefab
  Assets/Prefabs/Art/Props/Tennisfield.prefab.meta
  Assets/Scenes/Art/Scene_Dylan.unity
  Assets/Textures/T_Tennis_Field_D.png
  Assets/Textures/T_Tennis_Field_D.png.meta
Labels: art, new, ready for merge

#50 feature/route confetti
  Assets/Materials/Particles.meta
  Assets/Materials/Particles/M_Confetti_Particle.mat
  Assets/Materials/Particles/M_Confetti_Particle.mat.meta
  Assets/Materials/Particles/M_Fountain_Particle.mat
  Assets/Materials/Particles/M_Fountain_Particle.mat.meta
  Assets/Prefabs/Funcinal/Entities/Player.prefab
  Assets/Prefabs/Particles/Confetti.meta
  Assets/Prefabs/Particles/Confetti/PS_Confetti.prefab
  Assets/Prefabs/Particles/Confetti/PS_Confetti.prefab.meta
  Assets/Textures/Particles.meta
  Assets/Textures/Particles/T_Confetti.png
  Assets/Textures/Particles/T_Confetti.png.meta
  Assets/Textures/Particles/T_Raindrop.png
  Assets/Textures/Particles/T_Raindrop.png.meta
Labels: art, new, ready for merge

#49 Feature/photobook window
  Assets/Prefabs/Funcinal/Entities/Photo-Interactable.prefab
  Assets/Prefabs/Funcinal/Entities/Photo-Interactable.prefab.meta
  Assets/Prefabs/Funcinal/UI/Canvas/CameraPanel.prefab
  Assets/Prefabs/Funcinal/UI/Canvas/PhotoBook/Page.prefab
  Assets/Scenes/Sprint2.unity
  Assets/Scripts/Framework/GeoLocation/CoordinatesTransform.cs
  Assets/Scripts/Framework/PhoneCamera/CameraPermission.cs
  Assets/Scripts/Framework/PhoneCamera/PhotoInteractable.cs
  Assets/Scripts/Framework/ScriptableObjects/PhotoData.cs
  Assets/Scripts/UI/Canvas/PhotoBookSystem/Page.cs
  Assets/Scripts/UI/Canvas/PhotoBookSystem/PhotoBookWindow.cs
  Assets/Scripts/UI/Canvas/PhotoBookSystem/PhotoBookWindow.cs.meta
  Assets/Scripts/UI/Canvas/PhotoTaking/CameraPanel.cs
Labels: code, new, ready for merge, ready for testing

#51 Art/Statue
  Assets/Materials/M_Statue.mat
  Assets/Materials/M_Statue.mat.meta
  Assets/Models/SM_Statue.fbx
  Assets/Models/SM_Statue.fbx.meta
  Assets/Prefabs/Art/Props/Statue.prefab
  Assets/Prefabs/Art/Props/Statue.prefab.meta
  Assets/Scenes/Art/Scene_Dylan.unity
  Assets/Textures/T_Statue_D.png
  Assets/Textures/T_Statue_D.png.meta
Labels: art, new, ready for review

#46 readme/patch-4
  README.md
Labels: documentation, ready for review

#52 art/bsovillabons
  Assets/Materials/M_BSOVillaBons.mat
  Assets/Materials/M_BSOVillaBons.mat.meta
  Assets/Models/SM_BSOVillaBons.fbx
  Assets/Models/SM_BSOVillaBons.fbx.meta
  Assets/Prefabs/Art/Props/SM_BSOVillaBons.prefab
  Assets/Prefabs/Art/Props/SM_BSOVillaBons.prefab.meta
  Assets/Scenes/Art/TaquilaArt.unity
  Assets/Textures/T_BSOVillaBons_D.png
  Assets/Textures/T_BSOVillaBons_D.png.meta
Labels: art, new, ready for merge

#56 Art/PlayerIcon
  Assets/Sprites/T_Player_Icon.png
  Assets/Sprites/T_Player_Icon.png.meta
Labels: art, new, ready for review

#57 feature/player-icon-rotater
  Assets/Prefabs/Funcinal/Entities/Player.prefab
  Assets/Prefabs/Funcinal/Systems/Route.prefab
  Assets/Scripts/Player/IconRotater.cs
  Assets/Scripts/Player/IconRotater.cs.meta
  Assets/Scripts/Player/LocationUpdater.cs
Labels: code, new, ready for review

#59 feature/camera-adjustments
  Assets/Prefabs/Funcinal/Entities/Player.prefab
Labels: art, ready for review

#61 art/logo
  Assets/Sprites/T_Logo.png
  Assets/Sprites/T_Logo.png.meta
  ProjectSettings/ProjectSettings.asset
  ProjectSettings/QualitySettings.asset
Labels: art, new, ready for merge

#60 Art/kantoor
  Assets/Materials/M_Kantoor.mat
  Assets/Materials/M_Kantoor.mat.meta
  Assets/Models/SM_Kantoor.fbx
  Assets/Models/SM_Kantoor.fbx.meta
  Assets/Prefabs/Art/Props/Kantoor.prefab
  Assets/Prefabs/Art/Props/Kantoor.prefab.meta
  Assets/Scenes/Art/Scene_Lisa.unity
  Assets/Textures/T_Kantoor_D.jpg
  Assets/Textures/T_Kantoor_D.jpg.meta
Labels: art, new, ready for merge

#62 Feature/route waypoints
  Assets/Prefabs/Funcinal/Systems/Route.prefab
  Assets/Scenes/Testing/RouteWaypoints.unity
  Assets/Scenes/Testing/RouteWaypoints.unity.meta
Labels: new, ready for merge

#63 Art/correct-logo
  Assets/Sprites/T_Logo.png
  Assets/Sprites/T_Logo_Icon.png
  Assets/Sprites/T_Logo_Icon.png.meta
  ProjectSettings/ProjectSettings.asset
Labels: art, new, ready for merge

#64 Feature/scene building 3
  Assets/Editor/CoordinatesTransformEditor.cs
  Assets/Prefabs/Funcinal/Entities/Photo-Interactable.prefab
  Assets/Prefabs/Funcinal/Entities/Player.prefab
  Assets/Prefabs/Funcinal/UI/Canvas/Introduction/Introduction pop-up.prefab
  Assets/Prefabs/Funcinal/UI/Canvas/MainCanvas.prefab
  Assets/Prefabs/Funcinal/UI/Canvas/PhotoBook/Photobook.prefab
  Assets/Scenes/Sprint3.unity
  Assets/ScriptableObjects/Photos/CWGM.asset
  Assets/ScriptableObjects/Photos/Default Text.asset
  Assets/ScriptableObjects/Photos/Default Text.asset.meta
  Assets/ScriptableObjects/Photos/Fontein.asset
  Assets/ScriptableObjects/Photos/Fontein.asset.meta
  Assets/ScriptableObjects/Photos/Frankendael Hermitage.asset
  Assets/ScriptableObjects/Photos/Frankendael Hermitage.asset.meta
  Assets/ScriptableObjects/Photos/Frankendael Poort.asset
  Assets/ScriptableObjects/Photos/Frankendael Poort.asset.meta
  Assets/ScriptableObjects/Photos/Hotkerk.asset
  Assets/ScriptableObjects/Photos/Hotkerk.asset.meta
  Assets/ScriptableObjects/Photos/Kinderdag Verblijf.asset
  Assets/ScriptableObjects/Photos/Kinderdag Verblijf.asset.meta
  Assets/Scripts/Framework/GeoLocation/CoordinatesTransform.cs
  Assets/Scripts/Framework/PhoneCamera/PhotoInteractable.cs
  Assets/Scripts/Framework/SaveLoadSystem/Saver.cs
  Assets/Scripts/UI/Canvas/Introduction/IntroductionPopup.cs
  Assets/Scripts/UI/Canvas/PhotoBookSystem/Page.cs
  Assets/Scripts/UI/Canvas/PhotoBookSystem/PhotoBookWindow.cs
  Assets/Scripts/UI/Canvas/ResetProgressButton.cs
  Assets/Scripts/UI/Canvas/ResetProgressButton.cs.meta
  ProjectSettings/ProjectSettings.asset
Labels: code, ready for merge

#66 Art/IntroductionPhotos
  Assets/Prefabs/Funcinal/UI/Canvas/Introduction/Introduction pop-up.prefab
  Assets/Sprites/Introduction/UI_Introduction_1.png
  Assets/Sprites/Introduction/UI_Introduction_1.png.meta
  Assets/Sprites/Introduction/UI_Introduction_2.png
  Assets/Sprites/Introduction/UI_Introduction_2.png.meta
  Assets/Sprites/Introduction/UI_Introduction_3.png
  Assets/Sprites/Introduction/UI_Introduction_3.png.meta
  Assets/Sprites/Introduction/UI_Introduction_4.png
  Assets/Sprites/Introduction/UI_Introduction_4.png.meta
Labels: art, new, ready for merge

#65 Hotfix/player-gps
  Assets/Editor/CoordinatesTransformEditor.cs
  Assets/Prefabs/Funcinal/Entities/Player.prefab
  Assets/Scenes/Sprint3.unity
  Assets/Scripts/Framework/Enums/CoordinatesTransformType.cs
  Assets/Scripts/Framework/Enums/CoordinatesTransformType.cs.meta
  Assets/Scripts/Framework/Enums/EmptyFolder.txt
  Assets/Scripts/Framework/Enums/EmptyFolder.txt.meta
  Assets/Scripts/Framework/GeoLocation/CoordinatesTransform.cs
  Assets/Scripts/Framework/SaveLoadSystem/Saver.cs
  Assets/Scripts/UI/Canvas/GeoPositionText.cs
  Assets/Scripts/UI/Canvas/Introduction/IntroductionPopup.cs
  Assets/Scripts/UI/Canvas/PhotoBookSystem/PhotoBookWindow.cs
Labels: bug, code, ready for review

#70 Feature/UI-statemachine
  Assets/Prefabs/Funcinal/UI/Canvas/MainCanvas.prefab
  Assets/Scenes/Sprint3.unity
  Assets/Scripts/Framework/Enums/UIState.cs
  Assets/Scripts/Framework/Enums/UIState.cs.meta
  Assets/Scripts/UI/Canvas/PhotoTaking/PhotoTaker.cs
  Assets/Scripts/UI/Canvas/StateMachine.meta
  Assets/Scripts/UI/Canvas/StateMachine/StateChange.cs
  Assets/Scripts/UI/Canvas/StateMachine/StateChange.cs.meta
  Assets/Scripts/UI/Canvas/StateMachine/UIStateCaller.cs
  Assets/Scripts/UI/Canvas/StateMachine/UIStateCaller.cs.meta
  Assets/Scripts/UI/Canvas/StateMachine/UIStateManager.cs
  Assets/Scripts/UI/Canvas/StateMachine/UIStateManager.cs.meta
  Assets/Swzwij/Crayon/CrayonBox/StateMachine.png
  Assets/Swzwij/Crayon/CrayonBox/StateMachine.png.meta
Labels: code, new, ready for merge

#72 hotfix/MainCanvas
  Assets/Prefabs/Funcinal/UI/Canvas/MainCanvas.prefab
  Assets/Scenes/Sprint3.unity
Labels: bug, ready for merge

#73 readme/patch-5
  README.md
Labels: code, ready for merge
